---
sudo: required

language: python

services:
  - docker

install:
  - docker build -t converter converter

script:
  - docker run --rm -it -v $(pwd)/data:/data converter -noflat -pyramid-resolutions 4 -pyramid-scale 2 /data/wsi.fake /data/ome.tiff
  - docker-compose up -d

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
